###### This file implements an example of the proposed pipeline on PDX data sets

source("pdx.import.fn.R")
source("pdx.bdc1.R")
source("pdx.owl.linear.R")

## Generate the screening results
load("trts.by.cancer.rda")
dir1 = "dir/to/data/" 
dir2 = "dir/to/output/"  

## Run the import.pdx to combine the raw txt data sets
import.pdx(output.interim=T)


# supervised screening for prognostic biomarkers
for (i in 1:length(trts.by.cancer)) {
  tumor_type = names(trts.by.cancer)[i]
  for (j in 1:length(trts.by.cancer[[i]])) {
    trt_type = trts.by.cancer[[i]][j]
    R = rep(0, 2)
    #R[1] = "source('dir/to/code/pdx.bdc1.R')"
    #R[1] = "source('pdx.bdc1.R')"
    R[2] = sprintf("pdx.bdc1(tumor_type = '%s', trt_type = '%s', input_dir = '%s', output_dir = '%s')", tumor_type, trt_type, dir1, dir2)
    CMD = paste(R, collapse = "\n")
    #pathtoRfile = sprintf("dir/to/code/%s_%s_submit_pre.R", tumor_type, trt_type)
    pathtoRfile = sprintf("%s_%s_submit_pre.R", tumor_type, trt_type)
    write.table(CMD, file = pathtoRfile, quote = F, col.names = F, row.names = F)
    system(pathtoRfile)
  }
}

# # supervised screening for predictive biomarkers
# for (i in 1:length(trts.by.cancer)) {
#   tumor_type = names(trts.by.cancer)[i]
#   trts = trts.by.cancer[[i]]
#   # all combinations of two trt's
#   trt.comb = combn(trts, 2)
#   for (j in 1:dim(trt.comb)[2]) {
#     trt_type1 = trt.comb[1, j]
#     trt_type2 = trt.comb[2, j]
#     R = rep(0, 2)
#     R[1] = "source('dir/to/code/pdx.bdc2.R')"
#     R[2] = sprintf("pdx.bdc2(tumor_type = '%s', trt_type1 = '%s', trt_type2 = '%s', input_dir = '%s', output_dir = '%s')", tumor_type, trt_type1, trt_type2, dir1, dir2)
#     CMD = paste(R, collapse = "\n")
#     pathtoRfile = sprintf("dir/to/code/%s_%s_%s_submit_pre.R", tumor_type, trt_type1, trt_type2)
#     write.table(CMD, file = pathtoRfile, quote = F, col.names = F, row.names = F)
#     system(pathtoRfile)
#   }
# }
# 
# 
# ## Run DAE to generate the features for certain cancer/gene number
# ## DL_BRCA_50.py is generated by pdx.dl.master.R
# system("python3 DL_BRCA_50.py")
# 


# ## Run the pdx.owl.linear to fit OWL for certain cancer/gene number
owl_results = pdx.owl.linear(cancer.type = 'BRCA', outcome = 'Surv',
                     gene.data.file = 'BRCA.50.biomarkers.csv',
                     input_dir = 'dir/to/data', output_dir = 'dir/to/output',
                     c1s = 0:5, c2s = 1:9)
					 

					 

